services:
  - type: web
    name: insta-downloader
    env: python
    region: oregon
    buildCommand: pip install -r server/requirements.txt
    startCommand: uvicorn server.main:app --host 0.0.0.0 --port 10000
    free: true
